version: '3'
services:
  backend_cc:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - quickhotelnetwork

  frontend_cc:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend_cc
    networks:
      - quickhotelnetwork

networks:
  quickhotelnetwork:

